name: Build & Publish (gh-pages)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Always ensure a lockfile exists BEFORE running npm ci
      - name: Ensure lockfile, then install
        run: |
          set -e
          echo "Repo contents:"
          ls -la
          if [ -f package-lock.json ]; then
            echo "package-lock.json found -> using npm ci"
            npm ci
          else
            echo "No package-lock.json -> generating one, then using npm ci"
            npm install --package-lock-only --no-audit --no-fund
            test -f package-lock.json || (echo "Failed to generate lockfile" && exit 1)
            npm ci
          fi

      - name: Build & bundle
        run: npm run release

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./bundles
